apiVersion: v1
kind: Pod
metadata:
  name: kdebugtools
  labels:
    name: kdebugtools
spec:
  containers:
  - name: kdebugtools
    image: ghcr.io/globalmaksimum/k-debug-tools:2.0
    command: ["/bin/sh"]
    args: ["-c", "trap 'echo Received SIGTERM, shutting down gracefully; exit 0' TERM INT; echo Container started, sleeping...; sleep infinity & wait"]
    terminationGracePeriodSeconds: 20
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "0.5"
        memory: "256Mi"
